/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminCurrenciesRouteImport } from './routes/admin/currencies'
import { Route as AdminBroadcastsRouteImport } from './routes/admin/broadcasts'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as DashboardWorkflowIndexRouteImport } from './routes/dashboard/workflow/index'
import { Route as DashboardStoreIndexRouteImport } from './routes/dashboard/store/index'
import { Route as DashboardReviewIndexRouteImport } from './routes/dashboard/review/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products/new'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiCronSyncSocialRouteImport } from './routes/api/cron/sync-social'
import { Route as DashboardProductsIdEditRouteImport } from './routes/dashboard/products/$id.edit'
import { Route as ApiAuthMetaCallbackRouteImport } from './routes/api/auth/meta/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/admin/currencies',
  path: '/admin/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/admin/broadcasts',
  path: '/admin/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/admin/bot',
  path: '/admin/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowIndexRoute = DashboardWorkflowIndexRouteImport.update({
  id: '/dashboard/workflow/',
  path: '/dashboard/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreIndexRoute = DashboardStoreIndexRouteImport.update({
  id: '/dashboard/store/',
  path: '/dashboard/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewIndexRoute = DashboardReviewIndexRouteImport.update({
  id: '/dashboard/review/',
  path: '/dashboard/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/dashboard/products/',
  path: '/dashboard/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/dashboard/orders/',
  path: '/dashboard/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/dashboard/products/new',
  path: '/dashboard/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncSocialRoute = ApiCronSyncSocialRouteImport.update({
  id: '/api/cron/sync-social',
  path: '/api/cron/sync-social',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIdEditRoute = DashboardProductsIdEditRouteImport.update({
  id: '/dashboard/products/$id/edit',
  path: '/dashboard/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMetaCallbackRoute = ApiAuthMetaCallbackRouteImport.update({
  id: '/api/auth/meta/callback',
  path: '/api/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/sync-social': typeof ApiCronSyncSocialRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/cron/sync-social': typeof ApiCronSyncSocialRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/review': typeof DashboardReviewIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/workflow': typeof DashboardWorkflowIndexRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/sync-social': typeof ApiCronSyncSocialRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/api/cron/sync-social'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/review/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
    | '/api/auth/meta/callback'
    | '/dashboard/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin'
    | '/dashboard'
    | '/api/cron/sync-social'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/review'
    | '/dashboard/store'
    | '/dashboard/workflow'
    | '/api/auth/meta/callback'
    | '/dashboard/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/api/cron/sync-social'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/review/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
    | '/api/auth/meta/callback'
    | '/dashboard/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminStoresRoute: typeof AdminStoresRoute
  StoreSlugRoute: typeof StoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiCronSyncSocialRoute: typeof ApiCronSyncSocialRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardReviewIndexRoute: typeof DashboardReviewIndexRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
  DashboardWorkflowIndexRoute: typeof DashboardWorkflowIndexRoute
  ApiAuthMetaCallbackRoute: typeof ApiAuthMetaCallbackRoute
  DashboardProductsIdEditRoute: typeof DashboardProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/admin/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/admin/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflow/': {
      id: '/dashboard/workflow/'
      path: '/dashboard/workflow'
      fullPath: '/dashboard/workflow/'
      preLoaderRoute: typeof DashboardWorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/dashboard/store'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof DashboardStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/review/': {
      id: '/dashboard/review/'
      path: '/dashboard/review'
      fullPath: '/dashboard/review/'
      preLoaderRoute: typeof DashboardReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/dashboard/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-social': {
      id: '/api/cron/sync-social'
      path: '/api/cron/sync-social'
      fullPath: '/api/cron/sync-social'
      preLoaderRoute: typeof ApiCronSyncSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/$id/edit': {
      id: '/dashboard/products/$id/edit'
      path: '/dashboard/products/$id/edit'
      fullPath: '/dashboard/products/$id/edit'
      preLoaderRoute: typeof DashboardProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/meta/callback': {
      id: '/api/auth/meta/callback'
      path: '/api/auth/meta/callback'
      fullPath: '/api/auth/meta/callback'
      preLoaderRoute: typeof ApiAuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminBotRoute: AdminBotRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminStoresRoute: AdminStoresRoute,
  StoreSlugRoute: StoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiCronSyncSocialRoute: ApiCronSyncSocialRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardReviewIndexRoute: DashboardReviewIndexRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
  DashboardWorkflowIndexRoute: DashboardWorkflowIndexRoute,
  ApiAuthMetaCallbackRoute: ApiAuthMetaCallbackRoute,
  DashboardProductsIdEditRoute: DashboardProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
