/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminCurrenciesRouteImport } from './routes/admin/currencies'
import { Route as AdminBroadcastsRouteImport } from './routes/admin/broadcasts'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as DashboardWorkflowIndexRouteImport } from './routes/dashboard/workflow/index'
import { Route as DashboardStoreIndexRouteImport } from './routes/dashboard/store/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products/new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/admin/currencies',
  path: '/admin/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/admin/broadcasts',
  path: '/admin/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/admin/bot',
  path: '/admin/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowIndexRoute = DashboardWorkflowIndexRouteImport.update({
  id: '/dashboard/workflow/',
  path: '/dashboard/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreIndexRoute = DashboardStoreIndexRouteImport.update({
  id: '/dashboard/store/',
  path: '/dashboard/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/dashboard/products/',
  path: '/dashboard/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/dashboard/orders/',
  path: '/dashboard/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/dashboard/products/new',
  path: '/dashboard/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/workflow': typeof DashboardWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin'
    | '/dashboard'
    | '/dashboard/products/new'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/store'
    | '/dashboard/workflow'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/currencies'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/stores'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminStoresRoute: typeof AdminStoresRoute
  StoreSlugRoute: typeof StoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
  DashboardWorkflowIndexRoute: typeof DashboardWorkflowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/admin/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/admin/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflow/': {
      id: '/dashboard/workflow/'
      path: '/dashboard/workflow'
      fullPath: '/dashboard/workflow/'
      preLoaderRoute: typeof DashboardWorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/dashboard/store'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof DashboardStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/dashboard/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminBotRoute: AdminBotRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminStoresRoute: AdminStoresRoute,
  StoreSlugRoute: StoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
  DashboardWorkflowIndexRoute: DashboardWorkflowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
