/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MerchantAppRouteImport } from './routes/merchant-app'
import { Route as FRouteImport } from './routes/f'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as FSettingsRouteImport } from './routes/f_.settings'
import { Route as FNotificationsRouteImport } from './routes/f_.notifications'
import { Route as FAppRouteImport } from './routes/f_.app'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as CustomerDashboardRouteImport } from './routes/customer/dashboard'
import { Route as CustomerAuthRouteImport } from './routes/customer/auth'
import { Route as CustomerAppRouteImport } from './routes/customer/app'
import { Route as Customer_layoutRouteImport } from './routes/customer/__layout'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminMoreRouteImport } from './routes/admin/more'
import { Route as AdminMediatorsRouteImport } from './routes/admin/mediators'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFittersRouteImport } from './routes/admin/fitters'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCurrenciesRouteImport } from './routes/admin/currencies'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminBroadcastsRouteImport } from './routes/admin/broadcasts'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as DashboardWorkflowIndexRouteImport } from './routes/dashboard/workflow/index'
import { Route as DashboardStoreIndexRouteImport } from './routes/dashboard/store/index'
import { Route as DashboardReviewIndexRouteImport } from './routes/dashboard/review/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products/new'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiProductImageIdRouteImport } from './routes/api/product-image/$id'
import { Route as ApiMissingProductImageIdRouteImport } from './routes/api/missing-product-image/$id'
import { Route as ApiMerchantMobileRouteImport } from './routes/api/merchant/mobile'
import { Route as ApiFitterMobileRouteImport } from './routes/api/fitter/mobile'
import { Route as ApiCustomerMobileRouteImport } from './routes/api/customer/mobile'
import { Route as DashboardProductsIdEditRouteImport } from './routes/dashboard/products/$id/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAppRoute = MerchantAppRouteImport.update({
  id: '/merchant-app',
  path: '/merchant-app',
  getParentRoute: () => rootRouteImport,
} as any)
const FRoute = FRouteImport.update({
  id: '/f',
  path: '/f',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSettingsRoute = FSettingsRouteImport.update({
  id: '/f_/settings',
  path: '/f/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FNotificationsRoute = FNotificationsRouteImport.update({
  id: '/f_/notifications',
  path: '/f/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FAppRoute = FAppRouteImport.update({
  id: '/f_/app',
  path: '/f/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAuthRoute = CustomerAuthRouteImport.update({
  id: '/customer/auth',
  path: '/customer/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAppRoute = CustomerAppRouteImport.update({
  id: '/customer/app',
  path: '/customer/app',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer_layoutRoute = Customer_layoutRouteImport.update({
  id: '/customer/__layout',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/admin/more',
  path: '/admin/more',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediatorsRoute = AdminMediatorsRouteImport.update({
  id: '/admin/mediators',
  path: '/admin/mediators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFittersRoute = AdminFittersRouteImport.update({
  id: '/admin/fitters',
  path: '/admin/fitters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/admin/currencies',
  path: '/admin/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/admin/broadcasts',
  path: '/admin/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/admin/bot',
  path: '/admin/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowIndexRoute = DashboardWorkflowIndexRouteImport.update({
  id: '/dashboard/workflow/',
  path: '/dashboard/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreIndexRoute = DashboardStoreIndexRouteImport.update({
  id: '/dashboard/store/',
  path: '/dashboard/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewIndexRoute = DashboardReviewIndexRouteImport.update({
  id: '/dashboard/review/',
  path: '/dashboard/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/dashboard/products/',
  path: '/dashboard/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/dashboard/orders/',
  path: '/dashboard/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/dashboard/products/new',
  path: '/dashboard/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductImageIdRoute = ApiProductImageIdRouteImport.update({
  id: '/api/product-image/$id',
  path: '/api/product-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMissingProductImageIdRoute =
  ApiMissingProductImageIdRouteImport.update({
    id: '/api/missing-product-image/$id',
    path: '/api/missing-product-image/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMerchantMobileRoute = ApiMerchantMobileRouteImport.update({
  id: '/api/merchant/mobile',
  path: '/api/merchant/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFitterMobileRoute = ApiFitterMobileRouteImport.update({
  id: '/api/fitter/mobile',
  path: '/api/fitter/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerMobileRoute = ApiCustomerMobileRouteImport.update({
  id: '/api/customer/mobile',
  path: '/api/customer/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIdEditRoute = DashboardProductsIdEditRouteImport.update({
  id: '/dashboard/products/$id/edit',
  path: '/dashboard/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/f': typeof FRoute
  '/merchant-app': typeof MerchantAppRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/fitters': typeof AdminFittersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mediators': typeof AdminMediatorsRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/customer': typeof Customer_layoutRoute
  '/customer/app': typeof CustomerAppRoute
  '/customer/auth': typeof CustomerAuthRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/f/app': typeof FAppRoute
  '/f/notifications': typeof FNotificationsRoute
  '/f/settings': typeof FSettingsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/customer/mobile': typeof ApiCustomerMobileRoute
  '/api/fitter/mobile': typeof ApiFitterMobileRoute
  '/api/merchant/mobile': typeof ApiMerchantMobileRoute
  '/api/missing-product-image/$id': typeof ApiMissingProductImageIdRoute
  '/api/product-image/$id': typeof ApiProductImageIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/f': typeof FRoute
  '/merchant-app': typeof MerchantAppRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/fitters': typeof AdminFittersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mediators': typeof AdminMediatorsRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/app': typeof CustomerAppRoute
  '/customer/auth': typeof CustomerAuthRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/f/app': typeof FAppRoute
  '/f/notifications': typeof FNotificationsRoute
  '/f/settings': typeof FSettingsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/customer/mobile': typeof ApiCustomerMobileRoute
  '/api/fitter/mobile': typeof ApiFitterMobileRoute
  '/api/merchant/mobile': typeof ApiMerchantMobileRoute
  '/api/missing-product-image/$id': typeof ApiMissingProductImageIdRoute
  '/api/product-image/$id': typeof ApiProductImageIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/review': typeof DashboardReviewIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/workflow': typeof DashboardWorkflowIndexRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/f': typeof FRoute
  '/merchant-app': typeof MerchantAppRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/fitters': typeof AdminFittersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mediators': typeof AdminMediatorsRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/customer/__layout': typeof Customer_layoutRoute
  '/customer/app': typeof CustomerAppRoute
  '/customer/auth': typeof CustomerAuthRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/f_/app': typeof FAppRoute
  '/f_/notifications': typeof FNotificationsRoute
  '/f_/settings': typeof FSettingsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/customer/mobile': typeof ApiCustomerMobileRoute
  '/api/fitter/mobile': typeof ApiFitterMobileRoute
  '/api/merchant/mobile': typeof ApiMerchantMobileRoute
  '/api/missing-product-image/$id': typeof ApiMissingProductImageIdRoute
  '/api/product-image/$id': typeof ApiProductImageIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/workflow/': typeof DashboardWorkflowIndexRoute
  '/dashboard/products/$id/edit': typeof DashboardProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/f'
    | '/merchant-app'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/catalog'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/fitters'
    | '/admin/login'
    | '/admin/mediators'
    | '/admin/more'
    | '/admin/packages'
    | '/admin/stores'
    | '/customer'
    | '/customer/app'
    | '/customer/auth'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/f/app'
    | '/f/notifications'
    | '/f/settings'
    | '/store/$slug'
    | '/admin/'
    | '/customer/'
    | '/dashboard/'
    | '/api/customer/mobile'
    | '/api/fitter/mobile'
    | '/api/merchant/mobile'
    | '/api/missing-product-image/$id'
    | '/api/product-image/$id'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/review/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
    | '/dashboard/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/f'
    | '/merchant-app'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/catalog'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/fitters'
    | '/admin/login'
    | '/admin/mediators'
    | '/admin/more'
    | '/admin/packages'
    | '/admin/stores'
    | '/customer'
    | '/customer/app'
    | '/customer/auth'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/f/app'
    | '/f/notifications'
    | '/f/settings'
    | '/store/$slug'
    | '/admin'
    | '/dashboard'
    | '/api/customer/mobile'
    | '/api/fitter/mobile'
    | '/api/merchant/mobile'
    | '/api/missing-product-image/$id'
    | '/api/product-image/$id'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/review'
    | '/dashboard/store'
    | '/dashboard/workflow'
    | '/dashboard/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/f'
    | '/merchant-app'
    | '/privacy'
    | '/terms'
    | '/admin/bot'
    | '/admin/broadcasts'
    | '/admin/catalog'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/fitters'
    | '/admin/login'
    | '/admin/mediators'
    | '/admin/more'
    | '/admin/packages'
    | '/admin/stores'
    | '/customer/__layout'
    | '/customer/app'
    | '/customer/auth'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/f_/app'
    | '/f_/notifications'
    | '/f_/settings'
    | '/store/$slug'
    | '/admin/'
    | '/customer/'
    | '/dashboard/'
    | '/api/customer/mobile'
    | '/api/fitter/mobile'
    | '/api/merchant/mobile'
    | '/api/missing-product-image/$id'
    | '/api/product-image/$id'
    | '/api/whatsapp/webhook'
    | '/dashboard/products/new'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/review/'
    | '/dashboard/store/'
    | '/dashboard/workflow/'
    | '/dashboard/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  FRoute: typeof FRoute
  MerchantAppRoute: typeof MerchantAppRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFittersRoute: typeof AdminFittersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediatorsRoute: typeof AdminMediatorsRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminStoresRoute: typeof AdminStoresRoute
  Customer_layoutRoute: typeof Customer_layoutRoute
  CustomerAppRoute: typeof CustomerAppRoute
  CustomerAuthRoute: typeof CustomerAuthRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  FAppRoute: typeof FAppRoute
  FNotificationsRoute: typeof FNotificationsRoute
  FSettingsRoute: typeof FSettingsRoute
  StoreSlugRoute: typeof StoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiCustomerMobileRoute: typeof ApiCustomerMobileRoute
  ApiFitterMobileRoute: typeof ApiFitterMobileRoute
  ApiMerchantMobileRoute: typeof ApiMerchantMobileRoute
  ApiMissingProductImageIdRoute: typeof ApiMissingProductImageIdRoute
  ApiProductImageIdRoute: typeof ApiProductImageIdRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardReviewIndexRoute: typeof DashboardReviewIndexRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
  DashboardWorkflowIndexRoute: typeof DashboardWorkflowIndexRoute
  DashboardProductsIdEditRoute: typeof DashboardProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-app': {
      id: '/merchant-app'
      path: '/merchant-app'
      fullPath: '/merchant-app'
      preLoaderRoute: typeof MerchantAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f': {
      id: '/f'
      path: '/f'
      fullPath: '/f'
      preLoaderRoute: typeof FRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f_/settings': {
      id: '/f_/settings'
      path: '/f/settings'
      fullPath: '/f/settings'
      preLoaderRoute: typeof FSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f_/notifications': {
      id: '/f_/notifications'
      path: '/f/notifications'
      fullPath: '/f/notifications'
      preLoaderRoute: typeof FNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f_/app': {
      id: '/f_/app'
      path: '/f/app'
      fullPath: '/f/app'
      preLoaderRoute: typeof FAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/auth': {
      id: '/customer/auth'
      path: '/customer/auth'
      fullPath: '/customer/auth'
      preLoaderRoute: typeof CustomerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/app': {
      id: '/customer/app'
      path: '/customer/app'
      fullPath: '/customer/app'
      preLoaderRoute: typeof CustomerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/__layout': {
      id: '/customer/__layout'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof Customer_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/admin/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mediators': {
      id: '/admin/mediators'
      path: '/admin/mediators'
      fullPath: '/admin/mediators'
      preLoaderRoute: typeof AdminMediatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fitters': {
      id: '/admin/fitters'
      path: '/admin/fitters'
      fullPath: '/admin/fitters'
      preLoaderRoute: typeof AdminFittersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/admin/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/admin/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflow/': {
      id: '/dashboard/workflow/'
      path: '/dashboard/workflow'
      fullPath: '/dashboard/workflow/'
      preLoaderRoute: typeof DashboardWorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/dashboard/store'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof DashboardStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/review/': {
      id: '/dashboard/review/'
      path: '/dashboard/review'
      fullPath: '/dashboard/review/'
      preLoaderRoute: typeof DashboardReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/dashboard/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-image/$id': {
      id: '/api/product-image/$id'
      path: '/api/product-image/$id'
      fullPath: '/api/product-image/$id'
      preLoaderRoute: typeof ApiProductImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/missing-product-image/$id': {
      id: '/api/missing-product-image/$id'
      path: '/api/missing-product-image/$id'
      fullPath: '/api/missing-product-image/$id'
      preLoaderRoute: typeof ApiMissingProductImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchant/mobile': {
      id: '/api/merchant/mobile'
      path: '/api/merchant/mobile'
      fullPath: '/api/merchant/mobile'
      preLoaderRoute: typeof ApiMerchantMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fitter/mobile': {
      id: '/api/fitter/mobile'
      path: '/api/fitter/mobile'
      fullPath: '/api/fitter/mobile'
      preLoaderRoute: typeof ApiFitterMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/mobile': {
      id: '/api/customer/mobile'
      path: '/api/customer/mobile'
      fullPath: '/api/customer/mobile'
      preLoaderRoute: typeof ApiCustomerMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/$id/edit': {
      id: '/dashboard/products/$id/edit'
      path: '/dashboard/products/$id/edit'
      fullPath: '/dashboard/products/$id/edit'
      preLoaderRoute: typeof DashboardProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  FRoute: FRoute,
  MerchantAppRoute: MerchantAppRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminBotRoute: AdminBotRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFittersRoute: AdminFittersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediatorsRoute: AdminMediatorsRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminStoresRoute: AdminStoresRoute,
  Customer_layoutRoute: Customer_layoutRoute,
  CustomerAppRoute: CustomerAppRoute,
  CustomerAuthRoute: CustomerAuthRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  FAppRoute: FAppRoute,
  FNotificationsRoute: FNotificationsRoute,
  FSettingsRoute: FSettingsRoute,
  StoreSlugRoute: StoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiCustomerMobileRoute: ApiCustomerMobileRoute,
  ApiFitterMobileRoute: ApiFitterMobileRoute,
  ApiMerchantMobileRoute: ApiMerchantMobileRoute,
  ApiMissingProductImageIdRoute: ApiMissingProductImageIdRoute,
  ApiProductImageIdRoute: ApiProductImageIdRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardReviewIndexRoute: DashboardReviewIndexRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
  DashboardWorkflowIndexRoute: DashboardWorkflowIndexRoute,
  DashboardProductsIdEditRoute: DashboardProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
